services:
  db:
    image: postgres:16
    container_name: todo-db
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  todoapi:
    build: .
    container_name: todo-api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=todo_db;Username=todo;Password=password"
    depends_on:
      - db